{"name": "test_popular[params1-check1]", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"login\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.", "trace": "Fixture \"login\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code."}, "parameters": [{"name": "params", "value": "{'type': 'new'}"}, {"name": "check", "value": "{'code': 1}"}], "start": 1640754196996, "stop": 1640754196996, "uuid": "4955ae53-9813-492c-bfb9-541f24c3f117", "historyId": "23cc6d22d15e4d0ef0249a731b7cc6ba", "testCaseId": "e782efbbe0a08f019148996912e5ca9a", "fullName": "testcase.test_popular#test_popular", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('login1')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_popular"}, {"name": "host", "value": "CYHD-L-0025"}, {"name": "thread", "value": "22108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_popular"}]}