{"name": "test_popular[params0-check0]", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"login\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.", "trace": "Fixture \"login\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code."}, "parameters": [{"name": "params", "value": "{'type': 'popular'}"}, {"name": "check", "value": "{'code': 1}"}], "start": 1640754196947, "stop": 1640754196947, "uuid": "a1403255-d373-4b6b-a163-d72f389cbf8a", "historyId": "95e433924bfa5c5920b3ff2de264ffd8", "testCaseId": "e782efbbe0a08f019148996912e5ca9a", "fullName": "testcase.test_popular#test_popular", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('login1')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_popular"}, {"name": "host", "value": "CYHD-L-0025"}, {"name": "thread", "value": "22108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_popular"}]}